### ISSUE TITLE
Add ability to log more data to MQTT

### ISSUE THREAD

**Issue by puterboy** [1technophile/OpenMQTTGateway#2022]
Not sure if this is a feature request or a bug :)
The MQTT topic `LOGtoMQTT` seems to only log a single entry at startup/restart of the device detailing the reason for the startup, namely something like:
```
  "reason": 6,
  "uptime": 2490
```

Changing the Log Level in the GUI has no effect.
I (perhaps naively) expected changing the log level in the GUI to allow for more verbose logging to MQTT.

Would it make sense to allow for more verbose logging to MQTT so that you aren't restricted to logging via the serial interface which is a PITA when your receiver is distant from your PC work area.

**Comment by 1technophile** [comment]
we used to have an MQTT logger a few years ago but the quantity of messages were generating instabilities.
It may not be the case anymore with the central queue implementation.

**Comment by puterboy** [comment]
Perhaps instabilities were caused by the memory corruption bug in jsonQueue that is now fixed?

**Comment by 1technophile** [comment]
It may be.
I'm currently improving the mqtt msg publish frequency. Still encountering issues, this work could be a prereq to an mqtt log publication.

**Comment by puterboy** [comment]
Would still be good to get a way to get more verbose logging via MQTT.
For example, this would be important for some of my decoder debugging since the signals that are causing my crash are picked up only by my downstairs installation and not near my computer where I can connect to the serial port...

**Comment by puterboy** [comment]
Please keep open as this is valuable for debugging.

**Comment by puterboy** [comment]
Please keep open

**Comment by puterboy** [comment]
Please keep open

**Comment by puterboy** [comment]
please keep open

**Comment by puterboy** [comment]
Please keep open

**Comment by puterboy** [comment]
Please keep open

**Comment by puterboy** [comment]
Please keep open
